Description: Network resources for the Cream web app

Parameters:

  ProjectName:
    Description: Name of project
    Type: String

  Region:
    Description: Region in which network resources are deployed
    Type: String
    Default: 'us-east-1'
    AllowedValues:
      - 'us-east-1'


Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-VPC"

  PrivateSubnet1: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select 
        - 0
        - !Cidr
          - !GetAtt VPC.CidrBlock
          - 4
          - 8
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-Private1"

  PrivateSubnet2: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select 
        - 1
        - !Cidr
          - !GetAtt VPC.CidrBlock
          - 4
          - 8
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-Private2"

  PublicSubnet1: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select 
        - 2
        - !Cidr
          - !GetAtt VPC.CidrBlock
          - 4
          - 8
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-Public1"

  PublicSubnet2: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select 
        - 3
        - !Cidr
          - !GetAtt VPC.CidrBlock
          - 4
          - 8
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-Public2"
